// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [BatchSearchLinkProcesses][google.cloud.datacatalog.lineage.v1.Lineage.BatchSearchLinkProcesses].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.BatchSearchLinkProcesses]: <doc:Lineage/batchSearchLinkProcesses(request:)>
public struct BatchSearchLinkProcessesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location where you want to search.
  public var parent: Swift.String = Swift.String()

  /// Required. An array of links to check for their associated LineageProcesses.
  ///
  /// The maximum number of items in this array is 100.
  /// If the request contains more than 100 links, it returns the
  /// `INVALID_ARGUMENT` error.
  ///
  /// Format: `projects/{project}/locations/{location}/links/{link}`.
  public var links: [Swift.String] = []

  /// Optional. The maximum number of processes to return in a single page of the
  /// response. A page may contain fewer results than this value.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token received from a previous
  /// `BatchSearchLinkProcesses` call. Use it to get the next page.
  ///
  /// When requesting subsequent pages of a response, remember that
  /// all parameters must match the values you provided
  /// in the original request.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `BatchSearchLinkProcessesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchSearchLinkProcessesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.BatchSearchLinkProcessesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
