// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for
/// [BatchSearchLinkProcesses][google.cloud.datacatalog.lineage.v1.Lineage.BatchSearchLinkProcesses].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.BatchSearchLinkProcesses]: <doc:Lineage/batchSearchLinkProcesses(request:)>
public struct BatchSearchLinkProcessesResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// An array of processes associated with the specified links.
  public var processLinks: [ProcessLinks] = []

  /// The token to specify as `page_token` in the subsequent call to get the next
  /// page. Omitted if there are no more pages in the response.
  public var nextPageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `BatchSearchLinkProcessesResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchSearchLinkProcessesResponse().with { $0.processLinks = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.datacatalog.lineage.v1.BatchSearchLinkProcessesResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [ProcessLinks] {
    return self.processLinks
  }

  public func _nextPageToken() -> Swift.String {
    return self.nextPageToken
  }
}
