// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Lineage link between two entities.
public struct LineageLink: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The entity that is the **source** of this link.
  public var source: EntityReference? = nil

  /// The entity that is the **target** of this link.
  public var target: EntityReference? = nil

  /// Processes metadata associated with the link.
  public var processes: [LineageLink.LineageProcess] = []

  /// Describes how the target entity is dependent on the source entity.
  public var dependencyInfo: [LineageLink.DependencyInfo] = []

  /// Depth of the current link in the graph starting from 1.
  public var depth: Swift.Int32 = Swift.Int32()

  /// The location where the LineageEvent that created the link is stored.
  public var location: Swift.String = Swift.String()

  /// Initialize a new instance of `LineageLink`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineageLink().with { $0.source = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Process metadata for the link.
  public struct LineageProcess: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Process that created the link.
    public var process: Process? = nil

    /// Initialize a new instance of `LineageProcess`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LineageProcess().with { $0.process = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink.LineageProcess"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Dependency info describes how one entity is dependent on another.
  public struct DependencyInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The type of dependency.
    public var dependencyType: DependencyType = DependencyType()

    /// Initialize a new instance of `DependencyInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DependencyInfo().with { $0.dependencyType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink.DependencyInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageLink"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
