// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A lineage event represents an operation on assets. Within the operation, the
/// data flows from the source to the target defined in the links field.
public struct LineageEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the lineage event.
  /// Format:
  /// `projects/{project}/locations/{location}/processes/{process}/runs/{run}/lineageEvents/{lineage_event}`.
  /// Can be specified or auto-assigned.
  /// {lineage_event} must be not longer than 200 characters and only
  /// contain characters in a set: `a-zA-Z0-9_-:.`
  public var name: Swift.String = Swift.String()

  /// Optional. List of source-target pairs. Can't contain more than 100 tuples.
  public var links: [EventLink] = []

  /// Required. The beginning of the transformation which resulted in this
  /// lineage event. For streaming scenarios, it should be the beginning of the
  /// period from which the lineage is being reported.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The end of the transformation which resulted in this lineage
  /// event.  For streaming scenarios, it should be the end of the period from
  /// which the lineage is being reported.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Initialize a new instance of `LineageEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = LineageEvent().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.LineageEvent"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
