// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol LineageStub: Sendable {
    func processOpenLineageRunEvent(
      request: ProcessOpenLineageRunEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ProcessOpenLineageRunEventResponse

    func createProcess(
      request: CreateProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    func updateProcess(
      request: UpdateProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    func getProcess(
      request: GetProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Process

    func listProcesses(
      request: ListProcessesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListProcessesResponse

    func deleteProcess(
      request: DeleteProcessRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createRun(
      request: CreateRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    func updateRun(
      request: UpdateRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    func getRun(
      request: GetRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.Run

    func listRuns(
      request: ListRunsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListRunsResponse

    func deleteRun(
      request: DeleteRunRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createLineageEvent(
      request: CreateLineageEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent

    func getLineageEvent(
      request: GetLineageEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.LineageEvent

    func listLineageEvents(
      request: ListLineageEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.ListLineageEventsResponse

    func deleteLineageEvent(
      request: DeleteLineageEventRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func searchLinks(
      request: SearchLinksRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLinksResponse

    func batchSearchLinkProcesses(
      request: BatchSearchLinkProcessesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.BatchSearchLinkProcessesResponse

    func searchLineageStreaming(
      request: SearchLineageStreamingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDataCatalogLineageV1.SearchLineageStreamingResponse

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
