// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [ListProcesses][google.cloud.datacatalog.lineage.v1.Lineage.ListProcesses].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.ListProcesses]: <doc:Lineage/listProcesses(request:)>
public struct ListProcessesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The name of the project and its location that owns this
  /// collection of processes.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of processes to return. The service may return
  /// fewer than this value. If unspecified, at most 50 processes are
  /// returned. The maximum value is 100; values greater than 100 are cut to
  /// 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token received from a previous `ListProcesses` call.
  /// Specify it to get the next page.
  ///
  /// When paginating, all other parameters specified in this call must
  /// match the parameters of the call that provided the page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListProcessesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListProcessesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.ListProcessesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
