// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A lineage run represents an execution of a process that creates
/// lineage events.
public struct Run: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Immutable. The resource name of the run. Format:
  /// `projects/{project}/locations/{location}/processes/{process}/runs/{run}`.
  /// Can be specified or auto-assigned.
  /// {run} must be not longer than 200 characters and only
  /// contain characters in a set: `a-zA-Z0-9_-:.`
  public var name: Swift.String = Swift.String()

  /// Optional. A human-readable name you can set to display in a user interface.
  /// Must be not longer than 200 characters and only contain UTF-8 letters
  /// or numbers, spaces or characters like `_-:&.`
  public var displayName: Swift.String = Swift.String()

  /// Optional. The attributes of the run. Should only be used for the purpose of
  /// non-semantic management (classifying, describing or labeling the run).
  ///
  /// Up to 100 attributes are allowed.
  public var attributes: [Swift.String: GoogleCloudWkt.Value] = [:]

  /// Required. The timestamp of the start of the run.
  public var startTime: GoogleCloudWkt.Timestamp? = nil

  /// Optional. The timestamp of the end of the run.
  public var endTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. The state of the run.
  public var state: Run.State = Run.State()

  /// Initialize a new instance of `Run`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Run().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// The current state of the run.
  public enum State: Codable, Equatable, Sendable {
    /// The state is unknown. The true state may be any of the below or a
    /// different state that is not supported here explicitly.
    case unknown
    /// The run is still executing.
    case started
    /// The run completed.
    case completed
    /// The run failed.
    case failed
    /// The run aborted.
    case aborted
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unknown
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unknown: return 0
      case .started: return 1
      case .completed: return 2
      case .failed: return 3
      case .aborted: return 4
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unknown: return "UNKNOWN"
      case .started: return "STARTED"
      case .completed: return "COMPLETED"
      case .failed: return "FAILED"
      case .aborted: return "ABORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "UNKNOWN": self = .unknown
      case "STARTED": self = .started
      case "COMPLETED": self = .completed
      case "FAILED": self = .failed
      case "ABORTED": self = .aborted
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unknown
      case 1: self = .started
      case 2: self = .completed
      case 3: self = .failed
      case 4: self = .aborted
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unknown: return try container.encode(0)
      case .started: return try container.encode(1)
      case .completed: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .aborted: return try container.encode(4)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.Run"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
