// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [SearchLinks][google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.SearchLinks]: <doc:Lineage/searchLinks(request:)>
public struct SearchLinksRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location you want search in.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of links to return in a single page of the
  /// response. A page may contain fewer links than this value. If unspecified,
  /// at most 10 links are returned.
  ///
  /// Maximum value is 100; values greater than 100 are reduced to 100.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. The page token received from a previous `SearchLinksRequest`
  /// call. Use it to get the next page.
  ///
  /// When requesting subsequent pages of a response, remember that
  /// all parameters must match the values you provided
  /// in the original request.
  public var pageToken: Swift.String = Swift.String()

  /// The asset for which you want to retrieve links.
  public var criteria: OneOf_Criteria? = nil

  /// Initialize a new instance of `SearchLinksRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchLinksRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case source = "source"
    case target = "target"
    case sources = "sources"
    case targets = "targets"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)

    var criteria: OneOf_Criteria? = nil
    let criteriaCheckAndSet = {
      if criteria != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'criteria'"))
      }
      criteria = $0
    }
    if let source = try container.decodeIfPresent(EntityReference?.self, forKey: .source) {
      try criteriaCheckAndSet(.source(source))
    }
    if let target = try container.decodeIfPresent(EntityReference?.self, forKey: .target) {
      try criteriaCheckAndSet(.target(target))
    }
    if let sources = try container.decodeIfPresent(MultipleEntityReference?.self, forKey: .sources)
    {
      try criteriaCheckAndSet(.sources(sources))
    }
    if let targets = try container.decodeIfPresent(MultipleEntityReference?.self, forKey: .targets)
    {
      try criteriaCheckAndSet(.targets(targets))
    }
    self.criteria = criteria
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)

    if let choice = self.criteria {
      switch choice {
      case .source(let value):
        try container.encode(value, forKey: .source)
      case .target(let value):
        try container.encode(value, forKey: .target)
      case .sources(let value):
        try container.encode(value, forKey: .sources)
      case .targets(let value):
        try container.encode(value, forKey: .targets)
      }
    }
  }

  /// The asset for which you want to retrieve links.
  public enum OneOf_Criteria: Codable, Equatable, Sendable {
    /// Optional. Send asset information in the **source** field to retrieve all
    /// links that lead from the specified asset to downstream assets.
    indirect case source(EntityReference?)
    /// Optional. Send asset information in the **target** field to retrieve all
    /// links that lead from upstream assets to the specified asset.
    indirect case target(EntityReference?)
    /// Optional. Send a list of asset information in the **sources** field to
    /// retrieve all links that lead from the specified assets to downstream
    /// assets. This field is similar to the `source`
    /// [source][google.cloud.datacatalog.lineage.v1.SearchLinksRequest.source]
    /// field but allows providing multiple entities.
    /// All entities within the `MultipleEntityReference` must have the same
    /// `fully_qualified_name`.
    ///
    /// [google.cloud.datacatalog.lineage.v1.SearchLinksRequest.source]: <doc:SearchLinksRequest/source>
    indirect case sources(MultipleEntityReference?)
    /// Optional. Send a list of asset information in the **targets** field to
    /// retrieve all links that lead from upstream assets to the specified
    /// assets. This field is similar to the `target`
    /// [target][google.cloud.datacatalog.lineage.v1.SearchLinksRequest.target]
    /// field but allows providing multiple entities.
    /// All entities within the `MultipleEntityReference` must have the same
    /// `fully_qualified_name`.
    ///
    /// [google.cloud.datacatalog.lineage.v1.SearchLinksRequest.target]: <doc:SearchLinksRequest/target>
    indirect case targets(MultipleEntityReference?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLinksRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
