// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// Request message for
/// [SearchLineageStreaming][google.cloud.datacatalog.lineage.v1.Lineage.SearchLineageStreaming].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.SearchLineageStreaming]: <doc:Lineage/searchLineageStreaming(request:)>
public struct SearchLineageStreamingRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The project and location to initiate the search from.
  public var parent: Swift.String = Swift.String()

  /// Required. The locations to search in.
  public var locations: [Swift.String] = []

  /// Required. Criteria for the root of the search.
  public var rootCriteria: SearchLineageStreamingRequest.RootCriteria? = nil

  /// Required. Direction of the search.
  public var direction: SearchLineageStreamingRequest.SearchDirection =
    SearchLineageStreamingRequest.SearchDirection()

  /// Optional. Filters for the search.
  public var filters: SearchLineageStreamingRequest.SearchFilters? = nil

  /// Optional. Limits for the search.
  public var limits: SearchLineageStreamingRequest.SearchLimits? = nil

  /// Initialize a new instance of `SearchLineageStreamingRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SearchLineageStreamingRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Filters for the search.
  public struct SearchFilters: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Types of dependencies between entities to retrieve.
    /// If unspecified, all dependency types are returned.
    public var dependencyTypes: [DependencyType] = []

    /// Optional. Entity set restriction. If unspecified, the method returns all
    /// entities.
    public var entitySet: SearchLineageStreamingRequest.EntitySet =
      SearchLineageStreamingRequest.EntitySet()

    /// Optional. Time interval to search for lineage. If unspecified, all
    /// lineage is returned. Currently, at most one of `start_time` and
    /// `end_time` can be set.
    public var timeRange: GoogleType.Interval? = nil

    /// Initialize a new instance of `SearchFilters`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchFilters().with { $0.dependencyTypes = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLineageStreamingRequest.SearchFilters"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Limits for the search results.
  public struct SearchLimits: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The maximum depth of the search. The default value is 5 and
    /// maximum value is 100.
    public var maxDepth: Swift.Int32 = Swift.Int32()

    /// Optional. The maximum number of links to return in the response. The
    /// default value is 1_000 and the maximum value is 10_000.
    public var maxResults: Swift.Int32 = Swift.Int32()

    /// Optional. The maximum number of processes to return per link. The default
    /// value is 0 and the maximum value is 100. If this value is non-zero, the
    /// response will contain process names for the links. To retrieve full
    /// process details in the response, include `links.processes.process` in the
    /// [FieldMask](https://developers.google.com/workspace/docs/api/how-tos/field-masks#read_with_a_field_mask).
    public var maxProcessPerLink: Swift.Int32 = Swift.Int32()

    /// Initialize a new instance of `SearchLimits`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SearchLimits().with { $0.maxDepth = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLineageStreamingRequest.SearchLimits"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Criteria for the root of the search.
  public struct RootCriteria: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Criteria for the root of the search.
    public var criteria: OneOf_Criteria? = nil

    /// Initialize a new instance of `RootCriteria`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RootCriteria().with { $0.entities = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case entities = "entities"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var criteria: OneOf_Criteria? = nil
      let criteriaCheckAndSet = {
        if criteria != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'criteria'"))
        }
        criteria = $0
      }
      if let entities = try container.decodeIfPresent(
        MultipleEntityReference?.self, forKey: .entities)
      {
        try criteriaCheckAndSet(.entities(entities))
      }
      self.criteria = criteria
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.criteria {
        switch choice {
        case .entities(let value):
          try container.encode(value, forKey: .entities)
        }
      }
    }

    /// Criteria for the root of the search.
    public enum OneOf_Criteria: Codable, Equatable, Sendable {
      /// Optional. The entities to initiate the search from. Entities can be
      /// specified by FQN only, or by FQN and field. To search by FQN and all
      /// available fields for that FQN, use the wildcard `*` as the field value.
      indirect case entities(MultipleEntityReference?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLineageStreamingRequest.RootCriteria"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Direction of the search.
  public enum SearchDirection: Codable, Equatable, Sendable {
    /// Direction is unspecified.
    case unspecified
    /// Retrieve links that lead from the specified asset to downstream assets.
    case downstream
    /// Retrieve links that lead from upstream assets to the specified asset.
    case upstream
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .downstream: return 1
      case .upstream: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "SEARCH_DIRECTION_UNSPECIFIED"
      case .downstream: return "DOWNSTREAM"
      case .upstream: return "UPSTREAM"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SearchDirection/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "SEARCH_DIRECTION_UNSPECIFIED": self = .unspecified
      case "DOWNSTREAM": self = .downstream
      case "UPSTREAM": self = .upstream
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SearchDirection/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .downstream
      case 2: self = .upstream
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .downstream: return try container.encode(1)
      case .upstream: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Entity set restriction.
  public enum EntitySet: Codable, Equatable, Sendable {
    /// The entity set is unspecified. Returns all the data.
    case unspecified
    /// Returns entities with only FQN specified. For example, entities with the
    /// `field` field set are not returned.
    case entities
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .entities: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ENTITY_SET_UNSPECIFIED"
      case .entities: return "ENTITIES"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:EntitySet/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ENTITY_SET_UNSPECIFIED": self = .unspecified
      case "ENTITIES": self = .entities
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:EntitySet/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .entities
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .entities: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.SearchLineageStreamingRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
