// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [UpdateRun][google.cloud.datacatalog.lineage.v1.Lineage.UpdateRun].
///
/// [google.cloud.datacatalog.lineage.v1.Lineage.UpdateRun]: <doc:Lineage/updateRun(request:)>
public struct UpdateRunRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The lineage run to update.
  ///
  /// The run's `name` field is used to identify the run to update.
  ///
  /// Format:
  /// `projects/{project}/locations/{location}/processes/{process}/runs/{run}`.
  public var run: Run? = nil

  /// Optional. The list of fields to update. Currently not used. The whole
  /// message is updated.
  public var updateMask: GoogleCloudWkt.FieldMask? = nil

  /// Optional. If set to true and the run is not found, the request creates it.
  public var allowMissing: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `UpdateRunRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = UpdateRunRequest().with { $0.run = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datacatalog.lineage.v1.UpdateRunRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
